### ISSUE TITLE
Priyansh Sharma

### ISSUE THREAD

**Issue by priyanshshharma** [Hack-Club-SRM/HCSSoC#21]
## Student Application
Hack Club SRM is elated to have you as an attendee! Let's get started! 🎉
`Note: Submit one Application for each project you want to be a part of, you can submit at max 2 Applications.`

### Details
**Name**:
**GitHub Profile**:
**LinkedIn Profile**:
**Year of Study**:

**Name of Project**:
**Project Link**:

I am 🤝:
 - [ ] A Student of SRM Institute of Science and Technology, Kattankulathur
 - [ ] A Member of Hack Club SRM
`Note: Select all that are applicable.`

Checklist ✅:
 - [ ] I have read the [Code of Conduct](https://github.com/Hack-Club-SRM/Code-of-Conduct) of Hack Club SRM.
 - [ ] I am above 18 years of age.
 - [ ] I am currently enrolled at an educational institution.
 - [ ] I am open to feedback and constructive comments at all times.
 - [ ] I will be able to commit for *at least* an hour a day, contributing to the project(s) I have chosen.

`Note: By submitting this application you acknowledge that the decision undertaken by Hack Club SRM under any circumstances shall be final and conclusive. You agree to comply with and abide by all the rules for the event, set by Hack Club SRM.`

**Comment by aaishikasb** [comment]
Hey @priyanshshharma, you have not filled out any of the details asked.
