### ISSUE TITLE
[Student Application] - (Name of Participant)

### ISSUE THREAD

**Issue by 1psrishti** [Hack-Club-SRM/HCSSoC#23]
## Student Application
Hack Club SRM is elated to have you as an attendee! Let's get started! 🎉
`Note: Submit one Application for each project you want to be a part of, you can submit at max 2 Applications.`

### Details
**Name**: Srishti Rawat
**GitHub Profile**: https://github.com/1psrishti
**LinkedIn Profile**: https://www.linkedin.com/in/srishtirawat2002/
**Year of Study**: 2020-2024

**Name of Project**: Chatterbox
**Project Link**: https://github.com/Akash-Ramjyothi/Chatterbox

I am 🤝:
 - [x] A Student of SRM Institute of Science and Technology, Kattankulathur
 - [x] A Member of Hack Club SRM
`Note: Select all that are applicable.`

Checklist ✅:
 - [x] I have read the [Code of Conduct](https://github.com/Hack-Club-SRM/Code-of-Conduct) of Hack Club SRM.
 - [x] I am above 18 years of age.
 - [x] I am currently enrolled at an educational institution.
 - [x] I am open to feedback and constructive comments at all times.
 - [x] I will be able to commit for *at least* an hour a day, contributing to the project(s) I have chosen.

`Note: By submitting this application you acknowledge that the decision undertaken by Hack Club SRM under any circumstances shall be final and conclusive. You agree to comply with and abide by all the rules for the event, set by Hack Club SRM.`

**Comment by aaishikasb** [comment]
Still interested in participating?

**Comment by 1psrishti** [comment]
I created a new issue for the same because I didn't add my name in this one 😅
