### ISSUE TITLE
[Student Application] -Aditya Agarwal

### ISSUE THREAD

**Issue by adityaagarwal1710** [Hack-Club-SRM/HCSSoC#42]
## Student Application
Hack Club SRM is elated to have you as an attendee! Let's get started! 🎉
`Note: Submit one Application for each project you want to be a part of, you can submit at max 2 Applications.`

### Details
Aditya Agarwal
https://github.com/adityaagarwal1710?tab=repositories
https://www.linkedin.com/in/aditya-agarwal-928632190/
3rd year

Bus booking Application using python
https://github.com/adityaagarwal1710/Bus-Booking-System-Application-Using-Python

I am 🤝:
 - [ ] A Student of SRM Institute of Science and Technology, Kattankulathur
 - [ ] A Member of Hack Club SRM
`Note: Select all that are applicable.`

Checklist ✅:
 - [ ] I have read the [Code of Conduct](https://github.com/Hack-Club-SRM/Code-of-Conduct) of Hack Club SRM.
 -  I am above 18 years of age.
 - I am currently enrolled at an educational institution.
 -  I am open to feedback and constructive comments at all times.
 -  I will be able to commit for *at least* an hour a day, contributing to the project(s) I have chosen.

`Note: By submitting this application you acknowledge that the decision undertaken by Hack Club SRM under any circumstances shall be final and conclusive. You agree to comply with and abide by all the rules for the event, set by Hack Club SRM.`

**Comment by aaishikasb** [comment]
Hi, @adityaagarwal1710. You are supposed to pick up projects from the list given in the repository, unfortunately, you cannot work on projects of your own. Closing this application so you can open a new one. :)
Regards.
