### ISSUE TITLE
[Student Application] - (Kumar Harsh)

### ISSUE THREAD

**Issue by harsh6768-svg** [Hack-Club-SRM/HCSSoC#92]
## Student Application
Hack Club SRM is elated to have you as an attendee! Let's get started! 🎉
`Note: Submit one Application for each project you want to be a part of, you can submit at max 2 Applications.`

### Details
Name : Harsh Kumar
GitHub Profile : https://github.com/harsh6768-svg
LinkedIn Profile: https://www.linkedin.com/in/harsh-kumar-50a7a61a9/
Year of Study: 2 year

Name of Project : Daily Coding DS ALGO Practice
Project Link:  https://github.com/Ayush7614/Daily-Coding-DS-ALGO-Practice

I am 🤝:
 - [ ] A Student of SRM Institute of Science and Technology, Kattankulathur
 - [ ] A Member of Hack Club SRM
`Note: Select all that are applicable.`

Checklist ✅:
 - [x] I have read the [Code of Conduct](https://github.com/Hack-Club-SRM/Code-of-Conduct) of Hack Club SRM.
 - [x] I am above 18 years of age.
 - [x] I am currently enrolled at an educational institution.
 - [x] I am open to feedback and constructive comments at all times.
 - [x] I will be able to commit for *at least* an hour a day, contributing to the project(s) I have chosen.

`Note: By submitting this application you acknowledge that the decision undertaken by Hack Club SRM under any circumstances shall be final and conclusive. You agree to comply with and abide by all the rules for the event, set by Hack Club SRM.`

**Comment by harsh6768-svg** [comment]
@aaishikasb please can it be approved ??

**Comment by aaishikasb** [comment]
Hey @harsh6768-svg, unfortunately, the contributing period has already commenced and the deadline for submitting the Student Application was 18th June. I would request you to try again at our next edition! Warmest regards.
