### ISSUE TITLE
Regarding Hcssoc

### ISSUE THREAD

**Issue by siddhi-244** [Hack-Club-SRM/HCSSoC#95]
Has the program ended ? I have received no mail regarding it.

**Comment by aaishikasb** [comment]
Hi there, we are currently in the process of shortlisting all the qualified participants. We'll reach out to you super soon! Thanks for waiting!

**Comment by siddhi-244** [comment]
> Hi there, we are currently in the process of shortlisting all the qualified participants. We'll reach out to you super soon! Thanks for waiting!

Ok !Waiting😊
